# Default values for hdfs-flux.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  datanode: fluxproject/hdfs-dn-4k8s:0.1
  namenode: fluxproject/hdfs-nn-4k8s:0.1

persistence:
  datanode:
    accessMode: ReadWriteOnce
    size: 10Gi
  namenode:
    accessMode: ReadWriteOnce
    size: 10Gi

