apiVersion: v1
kind: Service
metadata:
  name: namenode
  labels:
    app: flux-nn-svc
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - protocol: TCP
      port: 8020
      name: namenode-port
    - protocol: TCP
      port: 50070
      name: namenode-port-ui
