apiVersion: v1
kind: Pod
metadata:
  name: namenode-1
  labels:
    app: flux-nn-pod
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  hostNetwork: true
  hostPID: true
  dnsPolicy: ClusterFirstWithHostNet
  containers:
    - name: namenode
      image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
      ports:
        - containerPort: 50070
        - containerPort: 8020
      env:
        - name: CLUSTER_NAME
          value: valtechSparkRosCluster
      envFrom:
        - configMapRef:
            name: hadoop-cm
      volumeMounts:
        - name: namenode-volume
          mountPath: /hadoop/dfs
  volumes:
    - name: namenode-volume
      persistentVolumeClaim:
       claimName: flux-nn-pvc
  nodeSelector:
    hdfs-namenode-selector: hdfs-namenode
