apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flux-nn-pvc
  labels:
    app: {{ template "hdfs-flux.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: hdfs-nn
spec:
  accessModes:
  - {{ .Values.persistence.namenode.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.namenode.size | quote }}
