apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: flux-ros-hadoop
  name: flux-ros-hadoop
  selfLink: /api/v1/namespaces/default/services/flux-ros-hadoop
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    run: flux-ros-hadoop
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
