# Default values for hdfs-pv flux.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

persistence:
  datanode:
    accessMode: ReadWriteOnce
    size: 10Gi
  namenode:
    accessMode: ReadWriteOnce
    size: 10Gi

